#
# ███████████████████████████████████████████████████████████████████████████████████████████████████
# █░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░███░░░░░░░░░░░░░░█
# █░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██████████░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀░░░░█░░▄▀▄▀▄▀▄▀▄▀░░█
# █░░░░░░▄▀░░░░░░█░░▄▀░░██████████░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░▄▀▄▀░░█░░▄▀░░░░░░░░░░█
# █████░░▄▀░░█████░░▄▀░░██████████░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░█████████
# █████░░▄▀░░█████░░▄▀░░██░░░░░░██░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░░░░░░░░░█
# █████░░▄▀░░█████░░▄▀░░██░░▄▀░░██░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█
# █████░░▄▀░░█████░░▄▀░░██░░▄▀░░██░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░░░░░░░░░█
# █████░░▄▀░░█████░░▄▀░░░░░░▄▀░░░░░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░█████████
# █████░░▄▀░░█████░░▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░▄▀▄▀░░█░░▄▀░░░░░░░░░░█
# █████░░▄▀░░█████░░▄▀░░░░░░▄▀░░░░░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀░░░░█░░▄▀▄▀▄▀▄▀▄▀░░█
# █████░░░░░░█████░░░░░░██░░░░░░██░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░███░░░░░░░░░░░░░░█
# ███████████████████████████████████████████████████████████████████████████████████████████████████
# Добро пожаловать в мой плагин TWFly
# /f команда для начала полёта (права: tw.fly - право что бы начать полёт, tw.admin - если элитры снимутся или сломаются то полёт не будет прекращён)

quitFly: "&cНадеюсь ты был на земеле :D"
flyStart: "&aУдачного полёта!"
elytraCheck: "&cНаденьте &c&nЭЛИТРЫ&c!"
noPermission: "&cНедостаточно прав для выполнения команды"
onlyPlayer: "&cДоступно только игроку!"
cooldown: "&cПодождите ещё {time} сек" # {time} меняется на время до окончания кд
noExp: "&cУ вас недостаточно опыта, нужен 30 уровень!"
expEnd: "&cУ вас закончился опыт, выш полёт был прекращён!"

levelToStart: 30 #какой нужен уровень для начала полёта
takeExpSecond: 10 #сколько будет сниматься опыта за 1 секунду
cooldownTime: 300000 #в мс сколько будет задержка на использование команды
isBreak: true #будут ли ломаться элитры при полёте
